chapters:
  - number: 'XIII'
    title: 'Embracing Ethics and Sustainability in Hairstyling'
    data_file: 'data/chapters/chapter-xiii.yaml'
    output_file: 'OEBPS/text/23-Chapter-XIII.xhtml'
  - number: 'XIV'
    title: 'The Impact of AI on the Beauty Industry'
    data_file: 'data/chapters/chapter-xiv.yaml'
    output_file: 'OEBPS/text/25-Chapter-XIV.xhtml'
  - number: 'XV'
    title: 'Cultivating Resilience and Well-being in Hairstyling'
    data_file: 'data/chapters/chapter-xv.yaml'
    output_file: 'OEBPS/text/26-Chapter-XV.xhtml'
  - number: 'XVI'
    title: 'Tresses and Textures: Embracing Diversity in Hairstyling'
    data_file: 'data/chapters/chapter-xvi.yaml'
    output_file: 'OEBPS/text/27-Chapter-XVI.xhtml'